Step3 - 회원가입(유효성 검사)
next-step/android-signup pull request #41
Opened 2024-08-08 11:39 UTC by oyj7677

SignTextField가 컴포넌트화 되어있어 하나씩 진행하지 못하였습니다.

이번 진행중 질문 남깁니다.

1. compose의 경우 userNameRegex, userNameErrorMsg와 같은 const val 값들은 어디에 선언하는게 좋나요? 
2. 다음 코드를 컴포넌트화 시켜 묶는다면 많은 파라미터가 생성된다고 생각들어 묶지 못했습니다.  이름, 메일, 비밀번호, 비밀번호 확인 등 반복되는데 컴포넌트화 시켜도 괜찮을까요?
```
Column {
                SignUpTextField(text = userName, label =  "UserName", onTextValueChange = { userName = it })
                InputErrorText(text = userName, errMsg =userNameErrorMsg , regex = userNameRegex)
            }
```
감사합니다.

2024-08-08 13:52 UTC, laco-dev requested changes
두 가지 측면에서 고민 해 볼 내용이 있습니다.

1. 재사용성은 충분한 케이스가 모인뒤에 고민해도 됩니다. 우선은 컴포넌트가 가져야 할 역할과 기능에 집중 해 주셔도 충분합니다.
2. UI 테스트는 실제 프로덕션에 작성한 컴포넌트를 테스트하게 됩니다. 
"그렇기 때문에 컴포넌트를 어떻게 테스트 가능하도록 만들까?" 라는 주제가 이번 강의의 최종적인 목표이자 핵심입니다.

한번에 많은 정보를 소화하지 않으셔도 괜찮습니다.
하나씩 배우는 과정을 하고 있으니까요 😄

2024-08-08 13:52 UTC, laco-dev commented on app/src/main/java/nextstep/signup/ui/screen/SignUpScreen.kt
> +            }
코드 정리는 한번씩 해주시면 좋겠어요!
리포매팅만 해주셔도 충분합니다.

2024-08-08 13:52 UTC, laco-dev commented on app/src/main/java/nextstep/signup/ui/screen/SignUpScreen.kt
> +            }
> 다음 코드를 컴포넌트화 시켜 묶는다면 많은 파라미터가 생성된다고 생각들어 묶지 못했습니다. 이름, 메일, 비밀번호, 비밀번호 확인 등 반복되는데 컴포넌트화 시켜도 괜찮을까요?

지난 2단계에서 이야기가 나왔던 재사용성 관련한 내용입니다.
모든 경우의 수를 고려하고 대응하려면 말씀하신 것 처럼 많은 파라미터와 반복이 발생할 지도 모릅니다.

그렇기에 4개의 컴포넌트를 새로이 만들어서 기능을 내부에 구현하고 테스트를 하도록 만들어 볼 수도 있겠습니다.
1. 이름을 입력하는 폼
2. 이메일 주소를 입력하는 폼
3. 비밀번호를 입력하는 폼
4. 비밀번호 확인을 입력하는 폼

```kotlin
UserNameTextField(
   userName = userName,
   onUserNameChange = { userName = it }
)
```

혹은 하나의 컴포넌트만 만들어서 재사용 하도록 할 수도 있겠죠.
```kotlin
SignUpTextField(
  value = userName,
  onValueChange = { userName = it },
  isHidden = boolean,
  placeholder = string,
  label = string,
  error = boolean,
  errorMessage = string
  ...
)

```
다만 이러한 경우, 파라미터가 너무 많이 발생할 지도 모르겠군요.

결과적으로 어디까지 컴포넌트화를 시켜야 하는가? 는 앞으로 컴포즈로 개발한다면 항상 따라오는 고민이에요.
여러번 경험을 쌓고 연습을 해보면서 익숙해지는 과정이 필요합니다.

2024-08-08 13:52 UTC, laco-dev commented on app/src/androidTest/java/nextstep/signup/study/SignUpScreenTest.kt
> +        private const val passwordConfirmErrorMsg = "비밀번호가 일치하지 않습니다."
위 테스트 코드는 학습 테스트입니다.

미션 요구사항은 다음과 같은데요.
> 작성한 컴포넌트에 대한 UI 테스트를 다음과 같이 만들어보자.

테스트 코드에 작성한 컴포넌트를 테스트 하는 것이 아닌,
프로덕션 코드에 작성한 컴포넌트를 테스트 하도록 만들어야 하겠습니다. 😓
만약 이 코드를 잘 작성하더라도 프로덕션은 잘못했을 수도 있으니까요.

앞선 의견을 참고해서 기능을 테스트 가능하도록 만드려면 
UserNameTextFieldTest, EmailTextFieldTest, PasswordTextFieldTest 등을 작성 해 볼 수 있습니다.
혹은 강의자료에 있는 것 처럼, InputValidationTest 하나에 같이 포함을 해 볼 수 있겠습니다.
*3단계 UI 테스트 항목을 잘 살펴 봐주세요!

2024-08-08 13:52 UTC, laco-dev commented on app/src/main/java/nextstep/signup/ui/component/InputErrorText.kt
> +}
유효성 검사가 반드시 Regex로만 이루어지지는 않을 수도 있어요.
그렇다면, 유효성 검사라는 로직은 이를 사용하는 곳에서 결정하도록 만들어 볼 수도 있습니다.

```kotlin
@Composable
fun InputErrorText(
  errorMessage: String,
  error: Boolean,
)

InputErrorText(
  errorMessage = "...",
  error = { userName.length > 8 },
)
```

2024-08-08 13:52 UTC, laco-dev commented on app/src/main/java/nextstep/signup/ui/screen/SignUpScreen.kt
> +const val passwordConfirmErrorMsg = "비밀번호가 일치하지 않습니다."
> compose의 경우 userNameRegex, userNameErrorMsg와 같은 const val 값들은 어디에 선언하는게 좋나요?

컴포저블 함수는 별도로 클래스같은 코드가 없기 때문에 컴포저블 함수가 위치한 파일의 상단 혹은 하단에 위치시키면 됩니다.

2024-08-08 15:33 UTC, oyj7677 commented on app/src/main/java/nextstep/signup/ui/screen/SignUpScreen.kt
> +            }
한 줄이 깔끔하다 생각했었습니다. 코드 포매팅에 신경쓰겠습니다.

2024-08-08 18:18 UTC, oyj7677 commented
정형화된 커밋을 많이 해보지 않아 커밋 메시지의 표현이 어색한 것 같습니다. 
혹시 보기 어려우시다면 조언 부탁드리겠습니다.

2024-08-09 04:29 UTC, laco-dev approved these changes
좋습니다.
컴포넌트를 어떻게 나누는가는 앞으로도 항상 고민해야 되는 주제입니다.

다음 미션에서 기능 요구사항과 프로그래밍 요구사항을 잘 살펴봐주세요.
리팩토링이 목표이기 때문에 개선 해 볼 점이 있다면 같이 챙겨봐주셔도 좋습니다.

2024-08-09 04:29 UTC, laco-dev commented on app/src/androidTest/java/nextstep/signup/InputValidationTest.kt
> +                )
좋습니다.
나아가서, SignUp 화면에 대한 전반적인 테스트를 만들어본다면 SignUpScreenTest로 Screen을 테스트 하는 방법이 있습니다.

```kotlin
SignUpScreen(
  userName: String,
  onUserNameChange: (String) -> Unit,
  email: String,
  password: String,
  passwordConfirm: String,
  ...
)
```

이렇게 되면 테스트를 위해 텍스트필드를 임의로 만들지 않을 수 있습니다.
이는 다음 단계에서 테스트에 대한 범위가 확장되는 것을 구현할 때 고려해보면 됩니다.

2024-08-09 04:29 UTC, laco-dev commented on app/src/androidTest/java/nextstep/signup/InputValidationTest.kt
> +        private const val passwordConfirmErrorMsg = "비밀번호가 일치하지 않습니다."
비밀번호가 일치하지 않는 경우도 테스트를 작성 해보세요

2024-08-09 04:29 UTC, laco-dev commented on app/src/main/java/nextstep/signup/ui/component/NSTextField.kt
> +private const val passwordConfirmErrorMsg = "비밀번호가 일치하지 않습니다."
안드로이드 개발하면서 strings.xml을 사용하는데요.
미션에서는 사용하지 않으신 이유가 있으실까요?

리소스를 가져와서 사용하는 방법도 연습해보면 좋기 때문에 한번 적용 해보시면 어떨까요?

2024-08-09 04:29 UTC, laco-dev commented on app/src/androidTest/java/nextstep/signup/InputValidationTest.kt
> +        private const val passwordConfirmErrorMsg = "비밀번호가 일치하지 않습니다."
마찬가지로 프로덕션 코드랑 텍스트가 중복되는데, 리소스를 이용해서 같은 문구를 가져올 수 있도록 도전 해보면 좋을 것 같아요

2024-08-09 04:29 UTC, laco-dev commented on README.md
> +- [] 비밀번호 확인 TextField 유효성 검사
체크표시가 들어가야겠군요

2024-08-09 04:30 UTC, merged

2024-08-09 05:46 UTC, oyj7677 commented on README.md
> +- [] 비밀번호 확인 TextField 유효성 검사
사소한 실수 발생하지 않도록 주의하겠습니다. 감사합니다.

2024-08-09 08:13 UTC, oyj7677 commented on app/src/main/java/nextstep/signup/ui/component/NSTextField.kt
> +private const val passwordConfirmErrorMsg = "비밀번호가 일치하지 않습니다."
단순하게 화면 구현만 생각하는 바람에 그랬습니다.
compose 에서는 stringResource를 사용하여 String리소스를 가져올 수 있다는 점도 이번에 처음 알게되었습니다. 감사합니다.

2024-08-09 08:15 UTC, oyj7677 commented on app/src/main/java/nextstep/signup/ui/component/NSTextField.kt
> +private const val passwordConfirmErrorMsg = "비밀번호가 일치하지 않습니다."
추가적인 질문으로 UI 학습 테스트 환경에서 
아래의 코드처럼 context를 선언하여 사용해도 될까요?
```
var context: Context = ApplicationProvider.getApplicationContext()
        composeTestRule
            .onNodeWithText(context.getString(R.string.err_msg_user_name))
            .assertExists()
```
composeTestRule.setContent의 내부에서는 stringResource를 사용하기에 하나의 함수에 String 리소스를 참조하는 방법이 2개나 존재하는 것이 괜찮은지 궁금합니다.

2024-08-09 08:16 UTC, oyj7677 commented on app/src/androidTest/java/nextstep/signup/InputValidationTest.kt
> +        private const val passwordConfirmErrorMsg = "비밀번호가 일치하지 않습니다."
하나의 리소스에서 관리하니까 String값이 변경되었을 때 실수를 방지할 수 있응 것 같습니다. 감사합니다.