Step4 - 회원가입(리팩터링)
next-step/android-signup pull request #84
Opened 2024-08-15 13:26 UTC by YiBeomSeok

# 회원가입 리팩터링 요구사항 반영 및 리뷰 내용 반영

안녕하세요 리뷰어님.

1. 4단계 미션에서는 에러 없이 채워진 경우에만 Sign Up 버튼을 활성화한다는 조건이 있어서 기존의 모든 값이 채워진 경우에만 버튼을 활성화하는 조건을 수정했습니다.

2. Sign Up 버튼을 클릭하면 회원가입이 완료되었다는 스낵바가 노출된다는 요구사항이 있어서 기존의 스낵바 노출 내용을 변경했습니다.

3. Step3에서 리뷰해주신 내용들 반영하였습니다.

### 질문

안드로이드 개발을 하다보면 2번과 같은 기존의 stringRes가 필요 없어지는 경우가 자주 발생하는데 이럴 때 기존 stringRes를 지우는 것을 깜빡하는 일도 빈번합니다.
xml코드의 경우에는 가령 `unused import`같은 경고도 안 해주기도 하고요.
혹시 관리 팁 같은게 있을까요?

2024-08-15 23:36 UTC, laco-dev requested changes
4단계 미션 고생하셨습니다.

분리가 이미 되어있는 상황이라, 전반적인 코드 개선 위주로 잘 해주셨네요.
크게 피드백 드릴 점은 없어 지난 미션에서 남겨주신 질문과 생각할 점만 남겨두었습니다.

반영 여부는 선택적으로 하시고, 따로 필요가 없다면 바로 리뷰 요청 주시면 되겠습니다.

2024-08-15 23:36 UTC, laco-dev commented on app/src/androidTest/java/nextstep/signup/ui/component/SignUpScreenTest.kt
> +    }
> 말씀해주신 내용에 대해 생각해보니, None이나 Blank 같은 상태들은 오류보다는 유효성 검사 결과에 가깝다는 의견에 동의하게 되었습니다. 실제로 결과를 나타내는 이름으로 변경하는 것이 코드의 의도를 더 명확하게 전달할 수 있을 것 같습니다.
특히, 유효성 검사 결과를 Error로 표현하는 것이 모호할 수 있다는 점에서, ValidationResult과 같은 명칭으로 변경하는 것이 더 적절할 것 같습니다.
한가지 궁금한점은 이러한 네이밍을 ~Result로 하기로 결정했을 때 프로젝트 전반에 걸쳐 일관된 네이밍 스타일을 유지하는 편이실까요?

프로젝트 전반 이라는 말이 정확히 어떤 의미인지 잘 이해를 못했는데요.
네이밍 스타일이라면 유지하려고 지향하는 편입니다.
아무래도 팀의 스타일을 배려하고 맞춰줄 필요가 있으니까요

2024-08-15 23:36 UTC, laco-dev commented on app/src/main/java/nextstep/signup/ui/component/SignUpScreen.kt
> +        NextStepTextField(
> 리뷰 감사드립니다! UserNameTextField와 같은 컴포저블로 분리하는 것이 가독성과 테스트 측면에서 장점이 있다는 점에 동의합니다.
다만, 현재 코드에서는 각 텍스트 필드가 어떤 역할을 하는지 충분히 직관적으로 파악할 수 있다고 생각합니다. 주석을 통해 코드의 의도를 명확히 전달하려고 했고, 컴포넌트 분리가 오히려 코드 흐름을 파편화할 가능성도 있다고 판단했습니다.
저는 주로 TextField처럼 기본적으로 제공되는 함수보다는 여러 컴포저블 함수들이 조합된 함수나 공통화된 양식이 필요할 때 컴포넌트를 분리하는 편인데, 이에 대해 어떻게 생각하실지 궁금합니다.

넵, 어느정도 동의합니다.
컴포넌트를 분리하는 조건은 여러개 있지만 제 개인적인 기준으로는 아래처럼 작성하는 것 같습니다.



1. 가독성 개선이 필요할 때 (코드가 길어짐)
2. 컴포넌트의 여러가지 케이스를 넣어보면서 미리보기를 구성할 때
3. 컴포넌트가 독립적인 기능을 가질 때
4. 컴포넌트에 대해서만 테스트를 작성할 때 (사실상 2번)
5. 재사용
6. 디자인 시안을 참고했을 때 분리가 필요하면
7. ...

아마 저라면 아래와 같이 만들어 봤을 것 같아요.
```kotlin
internal fun NameTextField(
   value: String,
   onValueChange: (String) -> Unit,
   error: NameError?
)
// 내부적으로 label을 결정
// 오류 타입에 따라 어떻게 그려지는지 내부에서 결정
```

결국 말씀주신 것 처럼 선택의 문제입니다만...
이번에는 이렇게 해 봤다면, 다른 미션에서는 또 저렇게 해 보는 것도 연습삼아 권장드려요!

2024-08-15 23:36 UTC, laco-dev commented on app/src/main/java/nextstep/signup/ui/component/NextStepTextField.kt
> +        }
저는 람다를 선택적으로 넘겨야 하는 상황이라면 가급적 null을 사용하는 편인데요.
```kotlin
supportingText: @Composable (() -> Unit)? = null,
```

슬롯 형태의 API 에서는, null이 아닐 경우 간격을 띄운다거나 UI 배치를 바꾼다거나 등의 내부 구현이 들어가는 경우가 있어요.
그렇기에 비어있는 람다를 넣으면서 레이아웃 배치가 바뀔 수 있는 문제가 있습니다.
지금은 문제가 되지 않아 보이지만, 나중에 비슷한 상황이 오면 참고 해보면 좋습니다.
https://developer.android.com/develop/ui/compose/layouts/basics?hl=ko#slot-based-layouts

2024-08-15 23:36 UTC, laco-dev commented on app/src/main/res/values/strings.xml
> +    <string name="complete_signup">회원가입이 완료되었습니다.</string>
> 안드로이드 개발을 하다보면 2번과 같은 기존의 stringRes가 필요 없어지는 경우가 자주 발생하는데 이럴 때 기존 stringRes를 지우는 것을 깜빡하는 일도 빈번합니다.
xml코드의 경우에는 가령 unused import같은 경고도 안 해주기도 하고요.
혹시 관리 팁 같은게 있을까요?

글로벌 대응을 위해 리소스를 별도로 관리하는 팀이 아닌 이상 코드 관리 차원에서는 어쩔 수 없이 발생하는 현상 같습니다 ㅠ

여러가지 해결 방법이 있겠지만, 저는 리소스를 재사용하는 것을 피하는 편입니다.
만약 아래와 같은 범용적인 이름이 있을 때, 이를 어디까지 재사용 하는지 파악이 어렵게 됩니다.
```xml
<string name="cancel">취소</string>
```

그래서 구현하는 피쳐랑 리소스를 1:1로 만들어서 지울 때 같이 관리를 하려고 합니다.

2024-08-19 07:55 UTC, YiBeomSeok commented on app/src/main/res/values/strings.xml
> +    <string name="complete_signup">회원가입이 완료되었습니다.</string>
감사합니다. 저도 리뷰어님 방식대로 시도해봐야겠네요 ㅎㅎ

2024-08-19 07:56 UTC, YiBeomSeok commented
리뷰 감사드립니다.

2024-08-19 12:07 UTC, laco-dev approved these changes
어느정도 개발에 익숙하신 듯 하여, 현업에서 처럼 리뷰하는 것 같았습니다.
컴포즈 관련해서도 남은 기간동안 많이 배워가시기를 응원하겠습니다.

2024-08-19 12:07 UTC, merged